version: 2
project_name: tfnotify
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: tfnotify
    main: ./cmd/tfnotify
    binary: tfnotify
    ldflags: 
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'
release:
  prerelease: auto
